import type { Metadata } from 'next'
import { ReactNode } from 'react'
import './globals.css'

import { Poppins } from 'next/font/google'
import ReactQueryContextProvider from '@/app/context/react-query.context'
import { Toaster } from '@/components/ui/sonner'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <ReactQueryContextProvider>
          {children}
          <Toaster richColors position={'top-right'} closeButton />
        </ReactQueryContextProvider>
      </body>
    </html>
  )
}
