import type { Metadata } from 'next'
import { ReactNode } from 'react'
import './globals.css'

import { Poppins } from 'next/font/google'
import ReactQueryContextProvider from '@/app/context/react-query.context'
import { Toaster } from '@/components/ui/sonner'
import { AuthContextProvider } from '@/app/context/auth.context'
import { ThemeProvider } from '@/app/context/theme-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryContextProvider>
            <AuthContextProvider>
              {children}
              <Toaster richColors position={'top-right'} closeButton />
            </AuthContextProvider>
          </ReactQueryContextProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
